# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share_to_social', '0003_auto_20160323_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('web_link', models.CharField(max_length=200)),
                ('event_time', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='twitter_profile',
            old_name='user_profile',
            new_name='user',
        ),
    ]
