# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 18:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('share_to_social', '0005_auto_20160323_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup_event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
