# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_to_social', '0006_auto_20160323_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup_event',
            name='photo_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
